# Your provided variables
alphabet = " abcdefghijklmnopqrstuvwxyz"
vowel = "aeiou"

# Assuming 'text_lines' is a list of lines from your text
text_lines = """
kskpnmmerynrthtullixbwjvfxsqdhngmphjjwgoaodzzalckqiqcybpgevf
phpqdrlmzxvbcdpygrfsjnnhmjgxlkfbmcsckftwvqslbqtyktdgwzhnrjzy
beiiruqwogjepegscounuaufnhoivqwczkxisezaeitaydfrmbdvaxoatlyp
sllkcwkqgfbfvpxkmmajcidjgwbtpsfouehidlvqmzagrnxdroceyhzyhtnj
dzfanraryeixewwztfndkhpqujgbxrsgumwpmtskcbeitsqylvhjavocvlox
suwgrkypinaxtlmdqejwkdhfrvevtpzfljzmrxynbhogstwcbcaisoeqvuax
flyjmtbdqrwhkggdhpzxhjjrwrtgzfmxkwykyvstmqfpsclvqclzpnsnxbvn
ydsvouygppgsoartmikxqftwvwulqwrfhsrnnzcaejvizabhcidjekxetlbm
pnmdcjftyflrmhtfbgzczxlzlddvpwjvskhgmwrcnsakqjbghybytswvxkxq
lzsbzmadprylvkukvennyiupatjepqqjqcogffxsbgatomsixrhtwhwdcnvr
ipbvjknhbztmxxlvjkmduldwlyggfhnmdcqjbefspcqarfkowzpnzghsyctr
xvrhnzvvqxtdsgdfsmcjbtjhyqkhbbglnflckwnkwzydpmrtlwpcfmpyjxgz
eajxoberlkidiucameeruwaovezlgpvmuaniwjkphnhuiiytatsqsooxofuq
twrxwviiadnapnlzhgmwqtfyigseoquovjsloarmpuekhuvjbxkcyedbcfzx
ehmqiguoxewpysooukliqsvjbrmprnebuxzzdnwifcueadlcaavyatatigof
qccnjdxbkwhwjpgkbtmnczgpqvyfstfvlbfgllwrvqpmsrdrxdyhnmtzjksh
twrqwzplkjdlcgsmvjpbxmhcfyzytqkrktnzvgsnlhfyaqrsbpjmgwvnxdhx
egadnhbcfvpoybgrsfcwlpeqziwaoebirqusxvoxytzkkcijmdhujzndmlta
zvfttzbgmfyrndwfgnzhdnskxvrchjwxmcphqclrlpybxwtgkvsqsmbydjqp
rncpzqoinqdfiwlbqbkojjasahevxpepiyxveduhcgfouwmtzamrkrstgyul
altcsqdwylhxhnpnwmtrgdkvawvsjybpvqujxebboxzqmyzpfisfrrtgnckz
gbfmhdvzlzvkdjpoljmwjwmkcknnqausarqelpiycznhggxytbxchdsftbrf
vzjbigyklxccfparvwezdbgyymgtdcjxqjnxwfplhhksuwhrmbkolstnzdfq
emutcmkqzaghgsiopnijlexdqoyujrwdwofevebxzcytlnfhrvaaipsuiabk
ldnmqfmwpbxtjxqhnczrbsyzchywykhbwpvdszclgnjvtlgprxfdrjgfkqkm
znooobmagvpfydueaxbaeeesxiehkjrstvuqoipiyalrwmqaitzuwniucuco
atjqburyyqcxozmpsbgnrfuaimkqxhevpcazguwlknoeirhpsftloivdejdw
brueyuwcegtqljaonboczakpauuvtrdgzkiaxdiqnfesslamopemifoyjhhi
tdjpklzwxflcnkgtghxqbkyjymmzgvrfqszfphbwrtdscdymbqnhjrcsvnlp
cdqgrfpxbkrmldlfxnipwvjbyryjhnttbshxdcqqzscazzpyewntgwkvmsvm
gkpqwwxfdbzjjlgdhrlvxsprgfncanmyfqtchkrbzkydqlcphmmyvstsbjzn
rcrnknpkpvnzefrflqauwbsijdaoghutegqysjmcmlpxbivqxeowiaydzoht
zlnftgdtqfklvlxqnkcpsdcyswwqhkfdcgmxyrtvjybprzrbbhmswnmpxjvz
iwzbeoxfmhxksyawrsdcpvyfqulgenmbuajndaveptiztilrsvtcqogwkohj
mqfkzoznwydrdhaoupsjinbepwvvtlxecasoqrjvektclgxbtgufiyisuham
iurfuvlgamtufdmenzyqijcdrkaslaxaswztoiixqooyenhbpjgheekpouvw
rczsjqxkbytpkzpmdvllbhbrqmvctfyswvdpfnmggfwjhytdxnqchgsxzwnr
qoawzxnpngjufrevqkczossbwafijvpbgilhadmumleyeiiahxruydttceko
fzebxvbmrfcmynthtynrqsspclmpotxdhifsvnuqzwjgdklkrqggkhplwajj
manqkjsqsjuslendfytkiwfgjovrrzlbtnmxcfqmrlzwyhcdhgpkpbxpavhg
vulewyempneyuujbvjoozoaahormgiixawxtqdafzichualrsenpqkistckb
kcwcgxioqdohrnnvuitzkpigxeporqwafjvmdimfyuylahsboleteueabjsa
cybfayfutwtgwzgkdbpjnrmllqbidmnsvdzefshccxvwqtxyvkqxhjrpzosr

""".strip().split("\n")  # Replace ... with the full text

# Function to decode each line
def decode_line(line):
    return alphabet[sum(1 for char in line if char in vowel)]

# Decode the entire message
decoded_message = ''.join(decode_line(line) for line in text_lines)

print(decoded_message)